import type { ApiEntry, ApiField } from './reference-data';
import type { Kit } from './snippets';
const field = (
  key: string,
  type: string,
  fallback: string,
  description: string,
  example: string,
): ApiField => ({
  key,
  type,
  default: fallback,
  description,
  example,
  required: fallback === 'Required',
  readOnly:
    (fallback !== 'Required' &&
      [
        'ratio / aa / aaa',
        'suggestedForeground',
        'history',
        'Theme.schemaVersion',
        'ThemeConfiguration.schemaVersion',
      ].includes(key)) ||
    (key === 'store' && fallback === 'Isolated draft'),
});
const item = (
  name: string,
  description: string,
  fields: ApiField[],
  kit: Kit,
  names: string,
  body: string,
): ApiEntry => ({
  id: name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-$/, ''),
  name,
  kind: 'Function',
  description,
  fields,
  example: {
    file: 'Usage.ts',
    code: `import { ${names} } from '@salyra-ui/${kit}';\n\n${body}`,
  },
});
const colors: ApiEntry[] = [
  item(
    'createColorHistory',
    'Keeps undo and redo steps for color and alpha edits. Changing the displayed format or surface does not add a step.',
    [
      field(
        'store',
        'ColorStore',
        'Required',
        'The color store to observe and restore.',
        'createColorHistory(store)',
      ),
      field(
        'options.limit',
        'positive integer',
        '100',
        'Maximum undo steps retained in memory. Older steps are dropped.',
        '{ limit: 50 }',
      ),
      field(
        'begin() / end()',
        '() => void',
        'No transaction',
        'Group several updates into one step. Transactions may be nested.',
        'history.begin(); store.setAlpha(.5); history.end();',
      ),
      field(
        'undo() / redo()',
        '() => void',
        'No effect at the end of history',
        'Restore color and alpha without changing format, view or disabled state. New edits discard the redo branch.',
        'history.undo()',
      ),
      field(
        'getSnapshot()',
        '{ canUndo, canRedo, length, index }',
        'One initial entry',
        'Read button availability. Subscribe to receive a new immutable snapshot after a history change.',
        'history.getSnapshot().canUndo',
      ),
      field(
        'clear() / destroy()',
        '() => void',
        'Explicit cleanup',
        'clear keeps the current value as the starting point. destroy releases subscriptions.',
        'history.destroy()',
      ),
    ],
    'color-picker',
    'createColorStore, createColorHistory',
    'const store = createColorStore("#5268E080");\nconst history = createColorHistory(store, { limit: 50 });\nhistory.begin();\nstore.setHex("#123456");\nstore.setAlpha(.5);\nhistory.end();\nhistory.undo();\nhistory.redo();\nhistory.destroy();',
  ),
  item(
    'mountHistory',
    'Groups pointer drags, held arrow keys and text-field edits on an editor root. Works with every framework.',
    [
      field(
        'root',
        'HTMLElement',
        'Required',
        'The editor element whose gestures belong to this history. Mount after the DOM exists.',
        'mountHistory(element, history)',
      ),
      field(
        'history',
        'HistoryController',
        'Required',
        'A color or theme history controller.',
        'createColorHistory(store)',
      ),
      field(
        'return value',
        '() => void',
        'Cleanup',
        'Remove root/document listeners and finish any open transaction. Call on unmount.',
        'detach()',
      ),
      field(
        'keyboard shortcut',
        'Ctrl/Cmd+Z, Shift+Ctrl/Cmd+Z',
        'Enabled outside editable fields',
        'Undo and redo on surfaces/buttons. Text inputs retain their native editing shortcuts.',
        'Focus the surface, then press Ctrl+Z.',
      ),
    ],
    'color-picker',
    'createColorStore, createColorHistory, mountHistory',
    'const history = createColorHistory(createColorStore());\nconst element = document.getElementById("editor")!;\nconst detach = mountHistory(element, history);\n// On unmount:\ndetach();\nhistory.destroy();',
  ),
  item(
    'bindColorForm',
    'Adds one real form field for the selected color. Handles native validation, disabled state and form reset.',
    [
      field(
        'root',
        'HTMLElement',
        'Required',
        'An element inside the form, or the form itself.',
        'bindColorForm(form, store, options)',
      ),
      field(
        'options.name',
        'nonempty string',
        'Required',
        'Key included in FormData and normal form submission.',
        '{ name: "brandColor" }',
      ),
      field(
        'options.format',
        "'hex' | 'rgb' | 'hsl' | 'hsv' | 'oklch' | 'oklab'",
        "'hex'",
        'Serialization format. HEX includes alpha. Other formats use the same strings as formatColor.',
        '{ format: "hsl" }',
      ),
      field(
        'options.defaultValue',
        'HEX string',
        'Current RGBA color at mount',
        'Color restored by an uncancelled form reset.',
        '{ defaultValue: "#5268E080" }',
      ),
      field(
        'options.required / disabled',
        'boolean',
        'false',
        'Native field constraints. Store disabled state also excludes the field from submission.',
        '{ required: true }',
      ),
      field(
        'options.validate',
        '(value: string) => string | undefined',
        'No custom validation',
        'Return an error message to make the field invalid, or undefined to accept the value.',
        '{ validate: value => value === "#000000" ? "Choose another color" : undefined }',
      ),
      field(
        'return value',
        '{ input, getValue(), destroy() }',
        'Mounted field',
        'Read the submitted string or clean up the field and reset listener.',
        'field.destroy()',
      ),
    ],
    'color-picker',
    'createColorStore, bindColorForm',
    'const store = createColorStore("#5268E080");\nconst form = document.querySelector<HTMLFormElement>("form")!;\nconst field = bindColorForm(form, store, { name: "brandColor", required: true });\nconsole.log(new FormData(form).get("brandColor"));\n// On unmount:\nfield.destroy();',
  ),
  item(
    'colorContrast',
    'Measures text contrast after compositing alpha over the background and canvas. It does not change the selected color.',
    [
      field(
        'foreground / background',
        'HEX strings with optional alpha',
        'Required',
        'Text color and the surface behind it.',
        'colorContrast("#00000080", "#FFFFFF")',
      ),
      field(
        'options.canvas',
        'opaque HEX string',
        "'#FFFFFF'",
        'Surface below a transparent background. Transparent canvases are rejected.',
        '{ canvas: "#171717" }',
      ),
      field(
        'options.text',
        "'normal' | 'large'",
        "'normal'",
        'Uses AA/AAA thresholds for normal or large text.',
        '{ text: "large" }',
      ),
      field(
        'ratio / aa / aaa',
        'number / boolean / boolean',
        'Calculated',
        'Full-precision contrast ratio and pass/fail results. Rounding is for display only.',
        'result.ratio.toFixed(2)',
      ),
      field(
        'suggestedForeground',
        'opaque HEX string',
        'Black or white',
        'The stronger of black and white on the rendered background. Apply only after user choice.',
        'store.setHex(result.suggestedForeground)',
      ),
    ],
    'color-picker',
    'colorContrast',
    'const result = colorContrast("#5268E080", "#FFFFFF");\nconsole.log(result.ratio, result.aa, result.aaa, result.suggestedForeground);',
  ),
  item(
    'createColorCollection',
    'Keeps bounded recent and favorite colors independently of theme roles. Persistence is optional and begins on load().',
    [
      field(
        'options.limit',
        'integer from 1 to 1000',
        '12',
        'Maximum colors in each list. HEX values are normalized and deduplicated.',
        '{ limit: 8 }',
      ),
      field(
        'options.favorites',
        'readonly HEX string[]',
        '[]',
        'Initial favorites before a valid saved collection is loaded.',
        '{ favorites: ["#5268E0", "#277D59"] }',
      ),
      field(
        'options.storage',
        '{ read(), write(snapshot) }',
        'No persistence',
        'Supply browserColorStorage(key) or your own synchronous storage adapter. Storage failures keep in-memory state usable.',
        '{ storage: browserColorStorage("app:colors") }',
      ),
      field(
        'load()',
        '() => void',
        'Explicit mount step',
        'Reads persistence. Call on the client so server and hydration snapshots remain identical.',
        'collection.load()',
      ),
      field(
        'remember(color)',
        '(HEX string) => void',
        'Explicit action',
        'Moves a color to the front of recent colors. Call after selection or Save, rather than on every drag sample.',
        'collection.remember(store.getSnapshot().value)',
      ),
      field(
        'toggleFavorite(color)',
        '(HEX string) => void',
        'Explicit action',
        'Adds or removes a favorite color.',
        'collection.toggleFavorite("#5268E0")',
      ),
      field(
        'getSnapshot() / subscribe()',
        'ColorCollectionSnapshot / subscription',
        'Immutable arrays',
        'Read recent and favorites arrays. Subscribe for UI updates. clearRecent() removes only recent colors.',
        'collection.getSnapshot().favorites',
      ),
    ],
    'color-picker',
    'createColorCollection, browserColorStorage',
    'const collection = createColorCollection({ favorites: ["#5268E0"], storage: browserColorStorage("app:colors") });\n// On client mount:\ncollection.load();\ncollection.remember("#12345680");\ncollection.toggleFavorite("#12345680");',
  ),
];
colors.push({
  id: 'colorcollection',
  name: 'ColorCollection',
  kind: 'Component',
  description:
    'Displays recent or favorite swatches and applies the selected value to the nearest color context.',
  fields: [
    field(
      'collection',
      'ColorCollectionStore',
      'Required',
      'Collection whose colors this component renders.',
      'collection={collection}',
    ),
    field(
      'kind',
      "'recent' | 'favorites'",
      "'recent'",
      'Selects one list. Use two components to show both lists.',
      'kind="favorites"',
    ),
    field(
      'label',
      'string',
      "'Recent colors'",
      'Visible legend. Set your own label when showing favorites.',
      'label="Saved brand colors"',
    ),
    field(
      'classes',
      '{ root?, item?, label? }',
      '{}',
      'Classes for the fieldset, each swatch container/button and legend. Color fill comes from the selected HEX value.',
      'classes={{ root: "brand-list", item: "brand-swatch", label: "brand-label" }}',
    ),
    field(
      'renderLabel',
      '(color: string) => ReactNode',
      'No item text',
      'React only. Supplies custom content for each color button. Vanilla mountColorCollection accepts a callback returning text. The Svelte, Vue and Angular presets support classes but do not accept a custom item renderer. Compose your own list with ColorSwatch when you need custom content.',
      'renderLabel={value => value}',
    ),
    field(
      'Astro colors',
      'readonly HEX string[]',
      '[]',
      'Astro renders serializable initial colors. On the client, cp-collection.setCollection(collection) connects a live collection.',
      'colors={["#5268E0"]}',
    ),
  ],
  example: {
    file: 'Collection.tsx',
    code: `import { useState } from 'react';\nimport { ColorProvider, ColorCollection, createColorCollection } from '@salyra-ui/color-picker/react';\nexport default function Collection() {\n  const [collection] = useState(() => createColorCollection({favorites:['#5268E0','#277D59']}));\n  return <ColorProvider><ColorCollection collection={collection} kind="favorites" label="Saved colors" classes={{item:'brand-swatch'}} /></ColorProvider>;\n}`,
  },
});
const themes: ApiEntry[] = [
  item(
    'createThemeEditor',
    'Creates a separate draft store that works with every provider. The applied store changes only on Apply unless live editing is enabled.',
    [
      field(
        'target',
        'ThemeStore',
        'Required',
        'Applied context to edit. Pass editor.store to the editor provider and keep target around the application preview.',
        'createThemeEditor(target)',
      ),
      field(
        'options.live',
        'boolean',
        'false',
        'Apply each draft change immediately. setLive(true) commits the current draft first.',
        '{ live: true }',
      ),
      field(
        'options.historyLimit',
        'positive integer',
        '100',
        'Maximum undo steps in editor.history.',
        '{ historyLimit: 50 }',
      ),
      field(
        'options.locked',
        'readonly ThemeLock[]',
        '[]',
        'Initial generation locks. primary, secondary, accent and background affect regeneration. Radius/width are already preserved by generation.',
        '{ locked: ["accent", "background"] }',
      ),
      field(
        'store',
        'ThemeStore',
        'Isolated draft',
        'Use existing picker, name, mode and geometry components against this store. Draft persistence is disabled by default.',
        '<ThemeProvider store={editor.store}>...</ThemeProvider>',
      ),
      field(
        'history',
        'HistoryController',
        'One initial entry',
        'Undo or redo draft edits. Use mountHistory(root, editor.history) to group drags and field edits.',
        'editor.history.undo()',
      ),
      field(
        'setLive(live)',
        '(boolean) => void',
        'false',
        'Enable immediate application or return to draft editing. Enabling commits the current draft.',
        'editor.setLive(true)',
      ),
      field(
        'subscribe(listener)',
        '(listener: () => void) => () => void',
        'Explicit subscription',
        'Observe dirty, conflict, live and locked state. The returned function unsubscribes.',
        'const unsubscribe = editor.subscribe(renderButtons)',
      ),
      field(
        'apply({ force? })',
        '({ force?: boolean }) => void',
        'force: false',
        'Commit theme and mode. A remote change during editing raises conflict. force explicitly replaces that newer applied theme.',
        'editor.apply({ force: true })',
      ),
      field(
        'cancel()',
        '() => void',
        'Explicit action',
        'Load the latest applied theme and mode, clear dirty/conflict state and reset draft history.',
        'editor.cancel()',
      ),
      field(
        'setLocked(field, locked?)',
        '(ThemeLock, boolean) => void',
        'locked: true',
        'Exclude a field from regeneration. Manual color editing remains available.',
        'editor.setLocked("accent", true)',
      ),
      field(
        'getSnapshot()',
        '{ dirty, conflict, live, locked }',
        'No edits',
        'State for Apply/Cancel buttons, conflict text and lock controls. Subscribe for changes.',
        'editor.getSnapshot().dirty',
      ),
      field(
        'destroy()',
        '() => void',
        'Explicit cleanup',
        'Remove source/draft subscriptions and dispose history. Detach mounted gesture listeners separately.',
        'editor.destroy()',
      ),
    ],
    'theme-studio',
    'createThemeStore, createThemeEditor',
    'const target = createThemeStore({modeStorage:false});\nconst editor = createThemeEditor(target, {locked:["accent"]});\neditor.store.setColor("primary", "#123456");\neditor.apply();\neditor.store.setName("Another draft");\neditor.cancel();\neditor.destroy();',
  ),
  item(
    'createThemeHistory',
    'Tracks theme and appearance preference changes. Loading status, disabled state, export field registration and system appearance changes do not add history steps.',
    [
      field(
        'store',
        'ThemeStore',
        'Required',
        'Applied or draft store whose editable values should be restored.',
        'createThemeHistory(store)',
      ),
      field(
        'options.limit',
        'positive integer',
        '100',
        'Maximum undo steps. Methods and gesture mounting match createColorHistory.',
        '{limit:50}',
      ),
      field(
        'begin() / end() / undo() / redo()',
        '() => void',
        'No transaction',
        'Group a drag or multiple setters and restore it as one action.',
        'history.begin(); store.setName("Brand"); history.end();',
      ),
    ],
    'theme-studio',
    'createThemeStore, createThemeHistory',
    'const store = createThemeStore();\nconst history = createThemeHistory(store);\nhistory.begin();\nstore.setName("Brand");\nstore.setBorder("radius", "card", .75);\nhistory.end();\nhistory.undo();\nhistory.destroy();',
  ),
  item(
    'themeTailwind',
    'Exports selected runtime variables and Tailwind 4 utility mappings. Colors map to bg/text utilities, radius to rounded utilities and width to custom border utilities.',
    [
      field(
        'state',
        'ThemeSnapshot',
        'Required',
        'Current theme and resolved appearance.',
        'themeTailwind(store.getSnapshot())',
      ),
      field(
        'options.selection',
        'TokenSelection',
        'Store selection, otherwise all tokens',
        'Only the configured roles, geometry and background are included. modes selects one or both appearance modes.',
        '{selection:{roles:["primary"],radius:["card"],width:["button"]}}',
      ),
      field(
        'options.selector',
        'CSS selector',
        "':root'",
        'Scope for runtime variables of the first exported appearance mode.',
        '{selector:".app-theme"}',
      ),
      field(
        'options.darkSelector',
        'CSS selector',
        "'.dark'",
        'Scope for dark variables when both modes are exported. Match the application class or data attribute.',
        '{darkSelector:\'.app-theme[data-mode="dark"]\'}',
      ),
      field(
        'return value',
        'string',
        'Tailwind CSS',
        'Import after Tailwind. bg-primary, text-primary-foreground, rounded-card and border-button exist only for exported fields.',
        'config.tailwind',
      ),
    ],
    'theme-studio',
    'createThemeStore, themeTailwind',
    'const store = createThemeStore({selection:{roles:["primary"],radius:["card"],width:["button"],background:true,modes:["light","dark"]}});\nconst css = themeTailwind(store.getSnapshot(), {selector:".app-theme",darkSelector:\'.app-theme[data-mode="dark"]\'});\nconsole.log(css);',
  ),
  item(
    'themeContrast',
    'Checks a theme role foreground against its default palette color using the same contrast result as colorContrast.',
    [
      field(
        'state',
        'ThemeSnapshot',
        'Required',
        'Theme to inspect.',
        'themeContrast(store.getSnapshot())',
      ),
      field(
        'role',
        "'primary' | 'secondary' | 'accent'",
        "'primary'",
        'Palette whose text/surface pair should be measured.',
        'themeContrast(store.getSnapshot(), "accent")',
      ),
      field(
        'return value',
        'ContrastResult',
        'Calculated',
        'ratio, aa, aaa and suggestedForeground. This helper does not modify the theme.',
        'result.aa',
      ),
    ],
    'theme-studio',
    'createThemeStore, themeContrast',
    'const store = createThemeStore();\nconst result = themeContrast(store.getSnapshot(), "primary");\nconsole.log(result.ratio, result.aa);',
  ),
  item(
    'createThemeCollection',
    'Keeps recent and favorite complete themes for your existing preset selector. Themes with the same ID replace the previous saved value.',
    [
      field(
        'options.limit',
        'integer from 1 to 1000',
        '12',
        'Maximum themes in each list.',
        '{limit:8}',
      ),
      field(
        'options.favorites',
        'readonly Theme[]',
        '[]',
        'Initial complete themes. Inputs are validated and frozen.',
        '{favorites:[generateTheme("#5268E0")]}',
      ),
      field(
        'options.storage',
        'ThemeCollectionStorage',
        'No persistence',
        'Use browserThemeCollectionStorage(key) or synchronous read/write methods. Call load() on client mount.',
        '{storage:browserThemeCollectionStorage("app:theme-library")}',
      ),
      field(
        'remember(theme) / toggleFavorite(theme)',
        '(Theme) => void',
        'Explicit action',
        'Store the applied theme after Apply, or toggle a favorite by its ID.',
        'collection.remember(store.getSnapshot().theme)',
      ),
      field(
        'getSnapshot()',
        '{ recent: readonly Theme[], favorites: readonly Theme[] }',
        'Immutable arrays',
        'Pass the favorites or recent list to ThemeSelect. Subscribe to keep a reactive list current.',
        'collection.getSnapshot().favorites',
      ),
    ],
    'theme-studio',
    'createThemeCollection, browserThemeCollectionStorage, generateTheme',
    'const collection = createThemeCollection({favorites:[generateTheme("#5268E0")],storage:browserThemeCollectionStorage("app:theme-library")});\n// On client mount:\ncollection.load();\ncollection.remember(generateTheme("#277D59"));',
  ),
  item(
    'Theme schema version',
    'Current themes and configuration exports use schemaVersion: 1. Older unversioned and version 0 themes are upgraded by parseTheme.',
    [
      field(
        'Theme.schemaVersion',
        '1',
        'Added by parseTheme',
        'Stored format version. Missing values on old input are accepted. Unsupported versions fail before being applied.',
        'parseTheme(saved).schemaVersion',
      ),
      field(
        'ThemeConfiguration.schemaVersion',
        '1',
        'Always present',
        'Version of exported configuration JSON. Partial exports still contain only selected fields.',
        'JSON.parse(config.json).schemaVersion',
      ),
      field(
        'mergeThemeConfiguration(base, saved)',
        'Theme',
        'Validated merge',
        'Load partial JSON over a full base. Version validation also applies to the merged theme.',
        'mergeThemeConfiguration(base, saved)',
      ),
    ],
    'theme-studio',
    'generateTheme, parseTheme',
    'const theme = generateTheme("#5268E0");\nconst saved = JSON.stringify(theme);\nconst restored = parseTheme(JSON.parse(saved));\nconsole.log(restored.schemaVersion);',
  ),
];
export function featureReferenceEntries(kit: Kit) {
  return kit === 'color-picker' ? colors : themes;
}
