/// <reference types="vite/client" />
import { mountColorPicker } from '@sebytza23/color-picker-vanilla';
import { mountThemeKit, generateTheme, themeModeActions, themeConfiguration, browserStorage, browserModeStorage } from '@sebytza23/theme-kit-vanilla';
import '@sebytza23/color-picker/styles.css';
import '@sebytza23/theme-kit/styles.css';
import './site.css';
import { examples, integrations, type Integration } from './snippets';
const app = document.querySelector<HTMLDivElement>('#app')!;
const page = document.body.dataset.page ?? 'docs';
const base = import.meta.env.BASE_URL;
const link = (file: string) => `${base}${file}`;
const logo = `<a class="brand" href="${link('site.html')}">theme<span>/</span>kit<i></i></a>`;
const nav = `<header class="site-nav">${logo}<nav><a href="${link('docs.html')}">Docs</a><a href="${link('color.html')}">Color picker</a><a href="${link('generator.html')}">Theme studio ↗</a><a href="https://github.com/sebytza23/theme-kit">GitHub</a></nav></header>`;
const footer = `<footer>${logo}<p>Made to fit your stack. Built to feel like yours.</p><a href="https://github.com/sebytza23/color-picker">color-picker ↗</a><a href="https://github.com/sebytza23/theme-kit">theme-kit ↗</a></footer>`;
const themes = [generateTheme('#6366f1', { name: 'Indigo' }), generateTheme('#ef6b52', { name: 'Coral' }), generateTheme('#277d59', { name: 'Forest' })];
if (page === 'landing') {
 app.innerHTML = `${nav}<main>
 <section class="hero"><div class="hero-copy"><span class="eyebrow"><b></b> TWO TOOLS. YOUR ENTIRE PALETTE.</span><h1>Give your app<br>a little <em>character.</em></h1><p>Pick a color. Build a theme. Make every surface feel like it belongs — in whatever framework feels like home.</p><div class="actions"><a class="button primary" href="${link('generator.html')}">Open theme studio <span>↗</span></a><a class="button" href="${link('docs.html')}">Explore the docs</a></div><div class="hero-note">Composable by design. Yours by default.</div></div>
 <div class="hero-art"><div class="art-top"><span>THEME / PLAYGROUND</span><span class="live-indicator">LIVE</span></div><div id="hero-color"></div><div id="hero-preview" class="art-preview"><div class="avatar-stack"><span>S</span><span>V</span><span>R</span></div><h3>A palette that<br>plays well together.</h3><p>The details make the difference.</p><button>Make it yours ↗</button><div class="art-chips"><i></i><i></i><i></i><i></i><i></i></div></div><div class="floating-label">your color, everywhere.</div></div></section>
 <div class="stack-strip"><span>AT HOME IN</span>${integrations.map(f => `<span>${f}</span>`).join('')}</div>
 <section class="section-intro"><span class="eyebrow">SMALL PIECES. BIG POSSIBILITIES.</span><h2>Start with a color.<br>Go as far as you want.</h2><p>Two focused kits, one shared language. Use the picker on its own, or let the theme kit turn your palette into a complete design system.</p></section>
 <section class="kit-cards"><article class="kit-card"><div class="kit-number">01 / COLOR PICKER</div><div class="spectrum-ribbon"></div><h3>Every color.<br>Every way.</h3><p>Rectangle or wheel. HEX, RGB, HSL, HSV, OKLCH and OKLab. Alpha, individual channel fields, color names and controls you can style down to the dot.</p><a href="${link('color.html')}">Meet color<span>/</span>picker ↗</a></article><article class="kit-card dark-card"><div class="kit-number">02 / THEME KIT</div><div class="palette-stack"><i></i><i></i><i></i></div><h3>A whole theme.<br>Your kind of theme.</h3><p>Three colors in harmony. Tinted surfaces. Borders and radii. System, light and dark. Share a context, choose a preset, or export your own.</p><a href="${link('generator.html')}">Build with theme<span>/</span>kit ↗</a></article></section>
 <section class="details-grid"><article><span>01</span><h3>Your markup. Your rules.</h3><p>Use our layout, compose the primitives, or build your own UI with stores and hooks.</p></article><article><span>02</span><h3>Only what you need.</h3><p>Independent framework adapters. A Svelte app installs the Svelte package and its core dependencies.</p></article><article><span>03</span><h3>Ready for the real app.</h3><p>SSR seeds, client loaders, custom loading content, fallback themes and cache revalidation.</p></article></section>
 <section class="final-cta"><span class="eyebrow">LESS SETUP. MORE MAKING.</span><h2>Your next theme<br>starts <em>here.</em></h2><a class="button primary" href="${link('generator.html')}">Let's make something ↗</a></section>
 </main>${footer}`;
 document.querySelector('.art-preview button')!.addEventListener('click', () => { window.location.href = link('generator.html'); });
 const preview = document.querySelector<HTMLElement>('#hero-preview')!;
 mountColorPicker(document.querySelector('#hero-color')!, { value: '#6366f1', view: 'wheel', onChange(color) {
   preview.style.setProperty('--hero-primary', color.hex); preview.style.setProperty('--hero-hue', String(color.hsl.h));
 }});
} else if (page === 'generator' || page === 'color') {
 const color = page === 'color';
 app.innerHTML = `${nav}<main class="studio"><div class="studio-heading"><span class="eyebrow">${color ? 'COLOR / PLAYGROUND' : 'THEME / STUDIO'}</span><h1>${color ? 'Find your color.' : 'Make it your theme.'}</h1><p>${color ? 'Every channel, every format, every shade of you.' : 'A palette, a shape, a mood. Build it here. Take it anywhere.'}</p></div><div class="studio-grid"><section class="studio-controls"><div id="studio-mount"></div></section><section class="studio-preview"><div class="preview-toolbar"><span>LIVE PREVIEW</span><span id="preview-name"></span></div><div id="preview-scope"><article class="sample-card"><div class="sample-tag">YOUR NEXT PROJECT</div><h2>Good things<br>have a good theme.</h2><p>Make room for a little personality.</p><div class="sample-buttons"><button class="sample-primary">Get started ↗</button><button class="sample-secondary">Explore</button></div><label class="sample-input">A little detail<input placeholder="Your next idea…" /></label><div class="sample-alert">✦ Made with your palette</div><div class="sample-swatches"><span></span><span></span><span></span></div></article></div><details open class="value-panel"><summary>${color ? 'Color name & values' : 'Your configuration'}</summary><pre id="studio-output"></pre></details><button class="button" id="download">Download ${color ? 'color' : 'theme'} JSON ↓</button></section></div></main>${footer}`;
 let json = '';
 const output = document.querySelector<HTMLElement>('#studio-output')!, scope = document.querySelector<HTMLElement>('#preview-scope')!, name = document.querySelector('#preview-name')!;
 if (color) mountColorPicker(document.querySelector('#studio-mount')!, { value: '#ef6b5280', view: 'wheel', onChange(c) {
   const t = generateTheme(c.hex.slice(0, 7)); scope.style.cssText = themeConfiguration({ ...createSnapshot(t) }).css;
   name.textContent = c.name; json = JSON.stringify(c, null, 2); output.textContent = json;
 }});
 else mountThemeKit(document.querySelector('#studio-mount')!, { fallbackTheme: themes[0], themes, storage: browserStorage('studio:theme'), modeStorage: browserModeStorage('studio:mode'), picker: { view: 'shared-wheel' }, onChange(config) {
   scope.style.cssText = config.css; name.textContent = config.theme.name; json = config.json; output.textContent = json;
 }});
 document.querySelector('#download')!.addEventListener('click', () => {
   const url = URL.createObjectURL(new Blob([json], { type: 'application/json' })), a = document.createElement('a'); a.href = url; a.download = color ? 'color.json' : 'theme.json'; a.click(); URL.revokeObjectURL(url);
 });
} else {
 app.innerHTML = `${nav}<div class="docs-layout"><aside><span class="eyebrow">DOCUMENTATION</span><a href="#getting-started">Getting started</a><a href="#color-picker">Color picker</a><a href="#theme-kit">Theme kit</a><a href="#rendering">Rendering & fallback</a><a href="#composition">Context & custom UI</a><a href="#persistence">Persistence & cache</a><a href="#examples">Framework examples</a><a href="#previews">Live implementations</a></aside><main class="docs-content">
 <section id="getting-started"><span class="eyebrow">BUILD SOMETHING THAT FEELS LIKE YOU.</span><h1>Two kits.<br>One good starting point.</h1><p class="lead">A framework independent core, native adapters, and all the pieces to make the UI your own.</p><div class="notice">Packages are prepared for publication under @sebytza23. Until the first npm release, use the local tarballs or clone the repositories and build them.</div><div class="framework-links"><a class="button" href="${link('downloads/color-picker.js')}" download>Color picker JS ↓</a><a class="button" href="${link('downloads/theme-kit.js')}" download>Theme kit JS ↓</a></div><h3>Choose your stack</h3><div id="install-tabs" class="tab-row"></div><pre id="install-code"></pre><p id="install-note"></p><p>Theme adapters depend on the matching color-picker adapter and both cores. React does not download Vue, Svelte or Angular. Framework peers come from your existing app.</p></section>
 <section id="color-picker"><span class="eyebrow">01 / COLOR PICKER</span><h2>Color in. Everything out.</h2><p>Use a rectangle or hue/saturation wheel, separate channel fields, alpha slider/input, format selection and a format cycle button. Formats: HEX, RGB, HSL, HSV, OKLCH, OKLab.</p><pre>const color = store.getColor();\ncolor.name;        // nearest name from the bundled color list\ncolor.exact;       // whether the named color is an exact match\ncolor.hex;         // #RRGGBB or #RRGGBBAA\ncolor.hsl;         // { h, s, l, alpha }\ncolor.oklch;       // { l, c, h, alpha }\ncolor.formats;     // strings for every supported format\nstore.getValue('hex'); // request just one format</pre><p>Color names are descriptive matches, not names supplied by users. Theme names can be overridden independently.</p><a class="inline-link" href="${link('color.html')}">Try the standalone color picker ↗</a></section>
 <section id="theme-kit"><span class="eyebrow">02 / THEME KIT</span><h2>A palette with a point of view.</h2><p>Generate primary, secondary and accent, choose analogous/triadic/split complementary harmony, or edit each color yourself. Share all three markers on one wheel, or show one anonymous dot.</p><p>Opt into tinted backgrounds. Edit border widths in pixels and radii in rem. Export only the roles and geometry tokens your UI actually uses.</p><pre>const theme = generateTheme('#6366f1', { name: 'Midnight', background: 'tinted' });\nstore.setName('My own theme'); // persists through color edits\nstore.setName(); // return to the suggested name\nconst config = themeConfiguration(store.getSnapshot());\n// { theme, mode, modePreference, systemMode, tokens, css, json }\nselectThemeTokens(config.theme, { roles: ['primary'], radius: ['card'] });</pre><a class="inline-link" href="${link('generator.html')}">Open the full theme studio ↗</a></section>
 <section id="rendering"><h2>Ready on the server.<br>Flexible in the browser.</h2><table><thead><tr><th>Mode</th><th>Initial render</th><th>After mount</th></tr></thead><tbody><tr><td>Standalone / SSR</td><td>Supply a resolved theme; tokens render immediately.</td><td>Interactive controls use the same context.</td></tr><tr><td>Client fetch</td><td>Fallback theme + your loading content.</td><td>Validated remote theme replaces fallback.</td></tr><tr><td>Fetch failure</td><td>Keep the configured loading view while pending.</td><td>Fallback theme, error state and optional retry.</td></tr><tr><td>System preference</td><td>Pass systemMode as a deterministic SSR seed.</td><td>Resolve matchMedia and follow OS changes.</td></tr></tbody></table><p>Each SSR request needs its own store. Keep the server theme/mode seed identical for hydration. The stored mode is restored after mount; supply a matching server seed when you want the initial render to match a saved preference.</p><pre>const options = {\n  fallbackTheme: generateTheme('#6366f1'),\n  mode: 'system', systemMode: 'light',\n  loadTheme: createHttpThemeLoader('/api/theme'),\n  timeoutMs: 10000,\n};\n// Compose ThemeLoading, ThemeReady and ThemeError around your own content.</pre></section>
 <section id="composition"><h2>Context at the top.<br>Creativity everywhere.</h2><p>Place ThemeProvider above your app. Every ThemePicker, ThemeSelect, ThemeName and ThemeExport inside that context reads or edits the same store. A nested provider creates an independent theme. Portals outside the CSS scope need explicit style/context wiring.</p><p>ThemeMode accepts a target value and custom children/snippets/slots/templates. Or use useThemeMode() to make buttons, a dropdown or a cycle control. It exposes preference, resolvedMode, setMode and cycle.</p><pre>// React: inside a descendant of ThemeProvider\nconst { preference, resolvedMode, setMode, cycle } = useThemeMode();\n// Svelte: const mode = useThemeMode(); $mode.preference\n// Vue: mode.preference.value; Angular: mode.preference()\n// Vanilla: themeModeActions(kit.store).setMode('system')</pre><p>Style classes and data-cp-part selectors control surfaces, markers, thumb text, input labels and tracks. CSS variables customize thumb size, radius, border, shadows and text. ColorPicker remains independent; connect onChange to store.setColor(role, color.hex) when composing your own theme editor.</p></section>
 <section id="persistence"><h2>A preference that stays.<br>A cache that can change.</h2><p>Mode persistence is enabled by default under theme-kit:mode. Use browserModeStorage('my-app:mode') for separate applications or modeStorage: false for isolated simulations. System follows the OS without replacing the saved system preference.</p><p>browserStorage persists the theme. On refresh, cached themes can paint while the loader revalidates; an explicit supplied theme takes priority. Same-origin storage events synchronize tabs. ETags, focus/polling checks and watchThemeUpdates notification hooks support external changes.</p><p>Your backend must provide ETags/revisions and optionally SSE/WebSocket notifications. Redis is optional; it does not notify the browser by itself.</p></section>
 <section id="examples"><h2>Pick your language.<br>Keep your freedom.</h2><div id="example-tabs" class="tab-row"></div><p id="example-note"></p><h3>Color picker</h3><pre id="color-code"></pre><h3>Theme kit</h3><pre id="theme-code"></pre></section>
 <section id="previews"><h2>Native implementations.</h2><p>Open each complete implementation. The studio above uses the vanilla adapter; the demos below use native framework components.</p><div class="framework-links">${['React','Svelte','Vue','Angular','Astro'].map(f => `<a class="button" href="${link(f === 'React' ? 'react.html' : f === 'Astro' ? 'demos/astro/index.html' : f.toLowerCase()+'.html')}">${f} demo ↗</a>`).join('')}</div></section>
 </main></div>${footer}`;
 const choose = (integration: Integration) => {
   const browserOnly = ['Vanilla','PHP','htmx'].includes(integration), suffix = browserOnly ? 'vanilla' : integration.toLowerCase();
   document.querySelector('#install-code')!.textContent = `npm install @sebytza23/color-picker-${suffix}\n# or the full theme editor for your stack\nnpm install @sebytza23/theme-kit-${suffix}`;
   document.querySelector('#install-note')!.textContent = browserOnly ? 'For plain HTML/PHP, copy browser/*.js and styles.css from the built vanilla packages. No npm process is needed on your PHP server.' : 'Import the adapter package in your existing framework app. Add both stylesheets for theme-kit.';
   document.querySelector('#example-note')!.textContent = examples[integration].note;
   document.querySelector('#color-code')!.textContent = examples[integration].color.replace(/@sebytza23\/color-picker(?=['"])/g, `@sebytza23/color-picker-${suffix}`).replace('@sebytza23/color-picker/styles.css', `@sebytza23/color-picker-${suffix}/styles.css`);
   document.querySelector('#theme-code')!.textContent = examples[integration].theme.replace(/@sebytza23\/theme-kit(?=['"])/g, `@sebytza23/theme-kit-${suffix}`).replace(/import '@sebytza23\/color-picker\/styles.css';\n/g, '').replace('@sebytza23/theme-kit/styles.css', `@sebytza23/theme-kit-${suffix}/styles.css`);
   document.querySelectorAll<HTMLButtonElement>('[data-integration]').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.integration === integration)));
 };
 for (const id of ['install-tabs','example-tabs']) for (const integration of integrations) {
   const button = document.createElement('button'); button.type = 'button'; button.dataset.integration = integration; button.textContent = integration; button.addEventListener('click', () => choose(integration)); document.querySelector('#'+id)!.append(button);
 }
 choose('Svelte');
}
function createSnapshot(theme: ReturnType<typeof generateTheme>): import('@sebytza23/theme-kit').ThemeSnapshot {
 // Core construction is request-local; this static preview deliberately has no browser persistence.
 return { theme, mode: 'light' as const, modePreference: 'light' as const, systemMode: 'light' as const, background: theme.backgroundMode ?? 'preserve', status: 'ready' as const, pending: false, error: null, style: '' };
}
