import { mkdtemp, writeFile, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
const consumer = await mkdtemp(join(tmpdir(), 'sebytza-kits-consumer-'));
const names = ['color-picker','theme-kit','color-picker-react','theme-kit-react','color-picker-vanilla','theme-kit-vanilla'];
const dependencies = Object.fromEntries(names.map(name => [`@sebytza23/${name}`, `file:${resolve('artifacts/scoped/sebytza23-'+name+'-0.1.0.tgz')}`]));
await writeFile(join(consumer,'package.json'), JSON.stringify({ private:true, type:'module', dependencies: { ...dependencies, react:'18.3.1', 'react-dom':'18.3.1', jsdom:'26.1.0' } }));
execFileSync('npm',['install','--ignore-scripts','--no-audit','--no-fund'],{cwd:consumer,stdio:'inherit'});
await writeFile(join(consumer,'smoke.mjs'), `import assert from 'node:assert/strict';
import { createElement as h } from 'react';
import { renderToString } from 'react-dom/server';
import { ThemeProvider, ThemeMode, ThemeName, generateTheme, createThemeStore } from '@sebytza23/theme-kit-react';
import { createColorStore } from '@sebytza23/color-picker-react';
const color = createColorStore('#12345680'); assert.equal(color.getColor().name, 'Prussian Blue');
const store = createThemeStore({ theme: generateTheme('#f00'), mode: 'system', systemMode: 'dark' });
store.setName('Packed theme'); store.setColor('primary','#00f'); assert.equal(store.getSnapshot().theme.name,'Packed theme');
assert.ok(renderToString(h(ThemeProvider,{store},h(ThemeMode,{value:'dark'},'Moon'))).includes('Moon'));
import { JSDOM } from 'jsdom';
const dom = new JSDOM('<body><div id="host"></div></body>',{url:'http://localhost'});
for (const key of ['window','document','HTMLElement','customElements','CustomEvent','Event','localStorage']) globalThis[key]=dom.window[key];
const { mountThemeKit } = await import('@sebytza23/theme-kit-vanilla');
const kit = mountThemeKit(document.querySelector('#host'),{theme:generateTheme('#6366f1'),modeStorage:false});
assert.equal(kit.getConfiguration().theme.name,generateTheme('#6366f1').name); kit.destroy();
console.log('Fresh consumer: scoped React SSR, native DOM, alpha/naming, modes and custom theme names passed.');
`);
execFileSync(process.execPath,['smoke.mjs'],{cwd:consumer,stdio:'inherit'});
const installed = JSON.parse(execFileSync('npm',['ls','--json','--all'],{cwd:consumer,encoding:'utf8'}));
const text = JSON.stringify(installed);
for (const unwanted of ['@sebytza23/color-picker-svelte','@sebytza23/color-picker-angular','@sebytza23/color-picker-vue','@sebytza23/theme-kit-astro']) if(text.includes(unwanted))throw new Error('Unexpected adapter installed: '+unwanted);
await writeFile('artifacts/scoped/consumer-directory.txt',consumer+'\n');
console.log('Only requested React/vanilla adapters were installed. No unrelated framework packages.');
